name: Update Packages

on:
  push:
    branches: [ master ]
  workflow_dispatch: # Enable manual trigger
    inputs:
      forced_packages:
        description: The list of packages to forcibly update (like "pkg1:ver1 pkg2")
        required: false
  schedule:
    - cron: '5 */4 * * *'

env:
  # Set au version to use or omit to use the latest. Specify branch name to use development version from Github
  au_version: master
  au_push: true
  # Use 1 to test all, or N to split testing into N groups
  au_test_groups: 1

  # Github token to commit pushed packages to repository
  github_user_repo: ${{ github.repository }}
  github_api_key: ${{ secrets.AU_GITHUB_API_KEY }}

  # Mail credentials - for error notifications
  mail_user: timtag1190@gmail.com
  mail_pass: ${{ secrets.MAILPASS }}
  mail_server: smtp.gmail.com
  mail_port: 587
  mail_enablessl: true

  #ID of the gist used to save run results
  gist_id: 508bb89c4cc35b67842940c60310532b

  #Chocolatey API key - to push updated packages
  api_key: ${{ secrets.CHOCO_API_KEY }}

  # GitHub Actions build url which points to this build
  GH_ACTIONS_BUILD_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  au:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v2

      - name: Check build environment
        run: |
          Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version
          $PSVersionTable
          git --version
          choco --version
          cmd /c "set" | grep -i 'github\|runner' | sort

      - name: Install wormies-au-helpers
        run: |
          Set-Service wuauserv -StartupType Manual
          cinst -y --no-progress wormies-au-helpers
          Set-Service wuauserv -StartupType Disabled

      - name: init
        run: |
          git config --global user.email "timtag1190@gmail.com"
          git config --global user.name "Journey"
          git config --global core.safecrlf false

      - name: Install AU
        run: |
          git clone -q https://github.com/majkinetor/au.git $Env:TEMP/au
          . "$Env:TEMP/au/scripts/Install-AU.ps1" $Env:au_version

      - name: Check update for packages
        run: |
          $ErrorActionPreference = 'Continue'
          ./update_all.ps1 -ForcedPackages '${{ github.event.inputs.forced_packages }}'
          7z a au_temp.zip $Env:TEMP\chocolatey\au\*

      - name: Upload update results
        uses: actions/upload-artifact@v2
        with:
          name: update_results
          path: |
            update_info.xml
            Update-AUPackages.md
            au_temp.zip
